### PR TITLE
BUG: Deleting initial field section causes all fields to be deleted in Work and Projects page.

### LINKED ISSUE #71: On delete all remaining section are getting deleted
**Describe the bug**
In the resume page in work and projects section if we try to add new fields section and try to delete the initial one and then again add new one and then try delete any of remaining fields section all fields sections are getting deleted and only after refreshing the page it's works as expected but again after deleting initial field section it creates same issue.

**video**

https://user-images.githubusercontent.com/68184118/235289032-dfbd1e58-1295-4c84-9996-63b899f89dc0.mp4

### PR DESCRIPTION
**Pull request by 777Prabhjot**
closes #71 

Hey it's done please check it out

### CODE REVIEW

**Comment by ShashwatAgrawal20** [comment]
hey @Khizarshah01 can you check on this one

File: src/components/ResumePage/element/BuildSteps/Work.js [hunk 1]
```diff
@@ -20,9 +20,17 @@ import { MdDelete } from "react-icons/md";
 
 const Work = () => {
   const { workList, setWorkList } = useResume();
-
+  console.log(workList)
```
Comment (ShashwatAgrawal20) [inline src/components/ResumePage/element/BuildSteps/Work.js:23]: can you remove this, as it's not supposed to be in the production

**Comment by ShashwatAgrawal20** [comment]
@777Prabhjot leaving a bit open for some testing

**Comment by ShashwatAgrawal20** [comment]
@Yashdon999 can you merge this if you have tested!!

**Comment by ShashwatAgrawal20** [comment]
Thanks @777Prabhjot for your contribution.
